# Generated by Django 2.0.5 on 2019-04-25 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='gwas_catalogue_ancestory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_accession', models.CharField(max_length=50)),
                ('pubmedid', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=50)),
                ('initial_sample_description', models.CharField(max_length=500)),
                ('stage', models.CharField(max_length=50)),
                ('number_of_individuals', models.IntegerField(default=20)),
                ('broad_acenstral_category', models.CharField(max_length=50)),
                ('country_of_origin', models.CharField(max_length=50)),
                ('country_of_recruitment', models.CharField(max_length=500)),
                ('additional_ancestry_description', models.CharField(max_length=500)),
            ],
        ),
    ]
