# Generated by Django 2.0.5 on 2019-04-25 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pm_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='gwas_catalogue_ancestory',
            table='gwas_catalogue_ancestory',
        ),
    ]
